export const food = [
  {
    id: 1,
    name: "Grilled Chicken Breast",
    ingredients: ["Chicken breast", "Olive oil", "Salt", "Pepper", "Garlic"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 284,
    protein: 53,
    carbs: 0,
    fat: 6,
    serving: "150g",
    mealType: "lunch",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["high_protein", "lean"],
    image: "https://source.unsplash.com/600x400/?grilled-chicken"
  },

  {
    id: 2,
    name: "Oatmeal with Berries",
    ingredients: ["Oats", "Milk", "Strawberries", "Blueberries", "Honey"],
    type: "veg",
    goal: "weight_loss",
    calories: 320,
    protein: 12,
    carbs: 55,
    fat: 5,
    serving: "1 bowl",
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["fiber_rich", "complex_carbs"],
    image: "https://source.unsplash.com/600x400/?oatmeal,berries"
  },

  {
    id: 3,
    name: "Rajma (Kidney Bean Curry)",
    ingredients: ["Kidney beans", "Onion", "Tomato", "Ginger", "Garlic", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 16,
    carbs: 55,
    fat: 5,
    serving: "1 bowl",
    mealType: "lunch",
    prepTime: "40 min",
    difficulty: "medium",
    tags: ["indian", "plant_protein"],
    image: "https://source.unsplash.com/600x400/?rajma,kidney-beans-curry"
  },

  {
    id: 4,
    name: "Salmon with Steamed Veggies",
    ingredients: ["Salmon", "Broccoli", "Carrot", "Olive oil", "Lemon"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 420,
    protein: 35,
    carbs: 8,
    fat: 28,
    serving: "180g",
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["omega_3", "high_protein"],
    image: "https://source.unsplash.com/600x400/?salmon,steamed-vegetables"
  },

  {
    id: 5,
    name: "Paneer Bhurji",
    ingredients: ["Paneer", "Onion", "Tomato", "Green chillies", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 380,
    protein: 22,
    carbs: 14,
    fat: 24,
    serving: "200g",
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["high_protein", "indian"],
    image: "https://source.unsplash.com/600x400/?paneer-bhurji,paneer"
  },

  {
    id: 6,
    name: "Greek Yogurt Parfait",
    ingredients: ["Greek yogurt", "Granola", "Berries", "Honey"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 20,
    carbs: 40,
    fat: 8,
    serving: "1 cup",
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["probiotic", "breakfast"],
    image: "https://source.unsplash.com/600x400/?greek-yogurt,parfait"
  },

  {
    id: 7,
    name: "Sweet Potato Mash",
    ingredients: ["Sweet potato", "Black pepper", "Salt"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 3,
    carbs: 41,
    fat: 0,
    serving: "150g",
    mealType: "lunch",
    prepTime: "12 min",
    difficulty: "easy",
    tags: ["complex_carbs", "fiber"],
    image: "https://source.unsplash.com/600x400/?sweet-potato,mash"
  },

  {
    id: 8,
    name: "Boiled Eggs",
    ingredients: ["Eggs", "Salt"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 155,
    protein: 13,
    carbs: 1,
    fat: 11,
    serving: "2 eggs",
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["protein"],
    image: "https://source.unsplash.com/600x400/?boiled-eggs"
  },

  {
    id: 9,
    name: "Sprouts Salad",
    ingredients: ["Mung sprouts", "Tomato", "Onion", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 130,
    protein: 9,
    carbs: 22,
    fat: 1,
    serving: "1 bowl",
    mealType: "snack",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["plant_protein", "raw"],
    image: "https://source.unsplash.com/600x400/?sprouts-salad"
  },

  {
    id: 10,
    name: "Chicken & Rice Bowl",
    ingredients: ["Chicken", "Brown rice", "Pepper", "Salt"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 510,
    protein: 38,
    carbs: 60,
    fat: 10,
    serving: "1 bowl",
    mealType: "lunch",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["gym_meal"],
    image: "https://source.unsplash.com/600x400/?chicken-rice,bowl"
  },

  {
    id: 11,
    name: "Avocado Toast",
    ingredients: ["Whole grain bread", "Avocado", "Salt", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 260,
    protein: 6,
    carbs: 26,
    fat: 14,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["healthy_fats"],
    image: "https://source.unsplash.com/600x400/?avocado-toast"
  },

  {
    id: 12,
    name: "Vegetable Stir Fry",
    ingredients: ["Broccoli", "Carrot", "Bell pepper", "Tofu", "Soy sauce"],
    type: "veg",
    goal: "weight_loss",
    calories: 220,
    protein: 12,
    carbs: 28,
    fat: 7,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["vegan"],
    image: "https://source.unsplash.com/600x400/?vegetable-stir-fry"
  },

  {
    id: 13,
    name: "Quinoa Salad",
    ingredients: ["Quinoa", "Cucumber", "Tomato", "Olive oil"],
    type: "veg",
    goal: "weight_loss",
    calories: 300,
    protein: 11,
    carbs: 34,
    fat: 9,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["plant_protein"],
    image: "https://source.unsplash.com/600x400/?quinoa-salad"
  },

  {
    id: 14,
    name: "Green Smoothie",
    ingredients: ["Spinach", "Banana", "Almond milk"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 3,
    carbs: 35,
    fat: 3,
    mealType: "snack",
    prepTime: "3 min",
    difficulty: "easy",
    tags: ["detox"],
    image: "https://source.unsplash.com/600x400/?green-smoothie"
  },

  {
    id: 15,
    name: "Chickpea Curry",
    ingredients: ["Chickpeas", "Tomato", "Onion", "Garlic", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 260,
    protein: 13,
    carbs: 36,
    fat: 7,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["indian", "vegan"],
    image: "https://source.unsplash.com/600x400/?chickpea-curry"
  },

  {
    id: 16,
    name: "Fruit Salad",
    ingredients: ["Apple", "Banana", "Grapes", "Orange"],
    type: "veg",
    goal: "weight_loss",
    calories: 150,
    protein: 2,
    carbs: 34,
    fat: 0,
    mealType: "snack",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["healthy"],
    image: "https://source.unsplash.com/600x400/?fruit-salad"
  },

  {
    id: 17,
    name: "Tofu Scramble",
    ingredients: ["Tofu", "Turmeric", "Spinach"],
    type: "veg",
    goal: "weight_loss",
    calories: 210,
    protein: 16,
    carbs: 8,
    fat: 12,
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["vegan"],
    image: "https://source.unsplash.com/600x400/?tofu-scramble"
  },

  {
    id: 18,
    name: "Grilled Fish",
    ingredients: ["White fish", "Lemon", "Garlic", "Pepper"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 250,
    protein: 30,
    carbs: 2,
    fat: 13,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["omega_3"],
    image: "https://source.unsplash.com/600x400/?grilled-fish"
  },

  {
    id: 19,
    name: "Banana Peanut Butter Toast",
    ingredients: ["Banana", "Whole wheat bread", "Peanut butter"],
    type: "veg",
    goal: "weight_gain",
    calories: 360,
    protein: 12,
    carbs: 42,
    fat: 16,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["bulk"],
    image: "https://source.unsplash.com/600x400/?banana-peanut-butter-toast"
  },

  {
    id: 20,
    name: "Masala Omelette",
    ingredients: ["Eggs", "Onion", "Tomato", "Coriander", "Chillies"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 220,
    protein: 16,
    carbs: 5,
    fat: 14,
    mealType: "breakfast",
    prepTime: "8 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?masala-omelette,omelette"
  },

  {
    id: 21,
    name: "Vegetable Soup",
    ingredients: ["Carrot", "Broccoli", "Beans", "Vegetable broth"],
    type: "veg",
    goal: "weight_loss",
    calories: 120,
    protein: 4,
    carbs: 20,
    fat: 2,
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["low_calorie"],
    image: "https://source.unsplash.com/600x400/?vegetable-soup"
  },

  {
    id: 22,
    name: "Chia Seed Pudding",
    ingredients: ["Chia seeds", "Milk", "Honey", "Strawberries"],
    type: "veg",
    goal: "weight_loss",
    calories: 250,
    protein: 8,
    carbs: 29,
    fat: 11,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["fiber"],
    image: "https://source.unsplash.com/600x400/?chia-pudding"
  },

  {
    id: 23,
    name: "Vegetable Upma",
    ingredients: ["Rava", "Carrot", "Peas", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 280,
    protein: 7,
    carbs: 46,
    fat: 7,
    mealType: "breakfast",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?upma,vegetable-upma"
  },

  {
    id: 24,
    name: "Grilled Paneer Tikka",
    ingredients: ["Paneer", "Spices", "Curd"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 21,
    carbs: 8,
    fat: 24,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["indian", "high_protein"],
    image: "https://source.unsplash.com/600x400/?paneer-tikka,grilled-paneer"
  },

  {
    id: 25,
    name: "Brown Rice Bowl",
    ingredients: ["Brown rice", "Beans", "Corn", "Peas"],
    type: "veg",
    goal: "weight_gain",
    calories: 410,
    protein: 12,
    carbs: 72,
    fat: 6,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["complex_carbs"],
    image: "https://source.unsplash.com/600x400/?brown-rice-bowl"
  },

  {
    id: 26,
    name: "Sautéed Spinach",
    ingredients: ["Spinach", "Garlic", "Olive oil"],
    type: "veg",
    goal: "weight_loss",
    calories: 120,
    protein: 5,
    carbs: 8,
    fat: 7,
    mealType: "dinner",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["nutrient_dense"],
    image: "https://source.unsplash.com/600x400/?sauteed-spinach,spinach"
  },

  {
    id: 27,
    name: "Broccoli Soup",
    ingredients: ["Broccoli", "Milk", "Black pepper"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 7,
    carbs: 20,
    fat: 7,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["fiber"],
    image: "https://source.unsplash.com/600x400/?broccoli-soup"
  },

  {
    id: 28,
    name: "Cottage Cheese Salad",
    ingredients: ["Paneer", "Lettuce", "Tomato"],
    type: "veg",
    goal: "weight_gain",
    calories: 260,
    protein: 20,
    carbs: 14,
    fat: 12,
    mealType: "lunch",
    prepTime: "8 min",
    difficulty: "easy",
    tags: ["protein"],
    image: "https://source.unsplash.com/600x400/?cottage-cheese-salad"
  },

  {
    id: 29,
    name: "Peanut Chutney",
    ingredients: ["Peanuts", "Garlic", "Red chilli"],
    type: "veg",
    goal: "weight_gain",
    calories: 210,
    protein: 9,
    carbs: 8,
    fat: 18,
    mealType: "snack",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["healthy_fats"],
    image: "https://source.unsplash.com/600x400/?peanut-chutney,peanuts"
  },

  {
    id: 30,
    name: "Steamed Dhokla",
    ingredients: ["Gram flour", "Yogurt", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 150,
    protein: 6,
    carbs: 22,
    fat: 4,
    mealType: "snack",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?dhokla,steamed-dhokla"
  },

  {
    id: 31,
    name: "Vegetable Khichdi",
    ingredients: ["Rice", "Lentils", "Vegetables"],
    type: "veg",
    goal: "weight_loss",
    calories: 310,
    protein: 13,
    carbs: 54,
    fat: 4,
    mealType: "dinner",
    prepTime: "30 min",
    difficulty: "easy",
    tags: ["indian", "comfort"],
    image: "https://source.unsplash.com/600x400/?khichdi,vegetable-khichdi"
  },

  {
    id: 32,
    name: "Egg Fried Rice (Healthy)",
    ingredients: ["Egg", "Brown rice", "Peas"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 480,
    protein: 22,
    carbs: 58,
    fat: 14,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["high_protein"],
    image: "https://source.unsplash.com/600x400/?egg-fried-rice"
  },

  {
    id: 33,
    name: "Poha",
    ingredients: ["Flattened rice", "Peas", "Onion", "Turmeric"],
    type: "veg",
    goal: "weight_loss",
    calories: 230,
    protein: 5,
    carbs: 40,
    fat: 5,
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?poha"
  },

  {
    id: 34,
    name: "Lemon Coriander Soup",
    ingredients: ["Coriander", "Lemon", "Vegetables"],
    type: "veg",
    goal: "weight_loss",
    calories: 90,
    protein: 3,
    carbs: 14,
    fat: 2,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["detox"],
    image: "https://source.unsplash.com/600x400/?lemon-coriander-soup"
  },

  {
    id: 35,
    name: "Hummus Bowl",
    ingredients: ["Chickpeas", "Tahini", "Olive oil", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 280,
    protein: 10,
    carbs: 24,
    fat: 14,
    mealType: "snack",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["mediterranean"],
    image: "https://source.unsplash.com/600x400/?hummus-bowl"
  },

  {
    id: 36,
    name: "Dal Tadka",
    ingredients: ["Lentils", "Garlic", "Ghee", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 320,
    protein: 18,
    carbs: 34,
    fat: 12,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?dal-tadka"
  },

  {
    id: 37,
    name: "Steamed Green Beans",
    ingredients: ["Green beans", "Salt"],
    type: "veg",
    goal: "weight_loss",
    calories: 90,
    protein: 3,
    carbs: 12,
    fat: 2,
    mealType: "lunch",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["light"],
    image: "https://source.unsplash.com/600x400/?green-beans,steamed-green-beans"
  },

  {
    id: 38,
    name: "Egg Curry",
    ingredients: ["Eggs", "Tomato", "Onion", "Spices"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 350,
    protein: 18,
    carbs: 14,
    fat: 22,
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["indian"],
    image: "https://source.unsplash.com/600x400/?egg-curry"
  },

  {
    id: 39,
    name: "Protein Smoothie",
    ingredients: ["Milk", "Banana", "Protein powder"],
    type: "veg",
    goal: "weight_gain",
    calories: 420,
    protein: 32,
    carbs: 48,
    fat: 10,
    mealType: "snack",
    prepTime: "3 min",
    difficulty: "easy",
    tags: ["shake"],
    image: "https://source.unsplash.com/600x400/?protein-smoothie"
  },

  {
    id: 40,
    name: "Veg Sandwich",
    ingredients: ["Whole wheat bread", "Cucumber", "Tomato", "Mint chutney"],
    type: "veg",
    goal: "weight_loss",
    calories: 210,
    protein: 6,
    carbs: 32,
    fat: 6,
    mealType: "snack",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["light"],
    image: "https://source.unsplash.com/600x400/?veg-sandwich"
  }
];
