export const food = [
  {
    id: 1,
    name: "Grilled Chicken Breast",
    ingredients: ["Chicken breast", "Olive oil", "Salt", "Pepper", "Garlic"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 284,
    protein: 53,
    carbs: 0,
    fat: 6,
    serving: "150g",
    mealType: "lunch",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["high_protein", "lean"],
    image: "https://cdn.pixabay.com/photo/2016/03/05/19/02/grilled-chicken-1239247_640.jpg"
  },

  {
    id: 2,
    name: "Oatmeal with Berries",
    ingredients: ["Oats", "Milk", "Strawberries", "Blueberries", "Honey"],
    type: "veg",
    goal: "weight_loss",
    calories: 320,
    protein: 12,
    carbs: 55,
    fat: 5,
    serving: "1 bowl",
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["fiber_rich", "complex_carbs"],
    image: "https://cdn.pixabay.com/photo/2017/03/31/23/45/berries-2195348_640.jpg"
  },

  {
    id: 3,
    name: "Rajma (Kidney Bean Curry)",
    ingredients: ["Kidney beans", "Onion", "Tomato", "Ginger", "Garlic", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 16,
    carbs: 55,
    fat: 5,
    serving: "1 bowl",
    mealType: "lunch",
    prepTime: "40 min",
    difficulty: "medium",
    tags: ["indian", "plant_protein"],
    image: "https://cdn.pixabay.com/photo/2020/05/17/17/25/kidney-bean-curry-5184193_640.jpg"
  },

  {
    id: 4,
    name: "Salmon with Steamed Veggies",
    ingredients: ["Salmon", "Broccoli", "Carrot", "Olive oil", "Lemon"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 420,
    protein: 35,
    carbs: 8,
    fat: 28,
    serving: "180g",
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["omega_3", "high_protein"],
    image: "https://cdn.pixabay.com/photo/2016/02/17/20/03/salmon-1208141_640.jpg"
  },

  {
    id: 5,
    name: "Paneer Bhurji",
    ingredients: ["Paneer", "Onion", "Tomato", "Green chillies", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 380,
    protein: 22,
    carbs: 14,
    fat: 24,
    serving: "200g",
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["high_protein", "indian"],
    image: "https://cdn.pixabay.com/photo/2023/01/20/09/35/paneer-7731398_640.jpg"
  },

  {
    id: 6,
    name: "Greek Yogurt Parfait",
    ingredients: ["Greek yogurt", "Granola", "Berries", "Honey"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 20,
    carbs: 40,
    fat: 8,
    serving: "1 cup",
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["probiotic", "breakfast"],
    image: "https://cdn.pixabay.com/photo/2017/02/13/15/00/yogurt-2065488_640.jpg"
  },

  {
    id: 7,
    name: "Sweet Potato Mash",
    ingredients: ["Sweet potato", "Black pepper", "Salt"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 3,
    carbs: 41,
    fat: 0,
    serving: "150g",
    mealType: "lunch",
    prepTime: "12 min",
    difficulty: "easy",
    tags: ["complex_carbs", "fiber"],
    image: "https://cdn.pixabay.com/photo/2020/11/28/09/25/sweet-potato-5784023_640.jpg"
  },

  {
    id: 8,
    name: "Boiled Eggs",
    ingredients: ["Eggs", "Salt"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 155,
    protein: 13,
    carbs: 1,
    fat: 11,
    serving: "2 eggs",
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["protein"],
    image: "https://cdn.pixabay.com/photo/2018/06/18/16/05/egg-3481397_640.jpg"
  },

  {
    id: 9,
    name: "Sprouts Salad",
    ingredients: ["Mung sprouts", "Tomato", "Onion", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 130,
    protein: 9,
    carbs: 22,
    fat: 1,
    serving: "1 bowl",
    mealType: "snack",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["plant_protein", "raw"],
    image: "https://cdn.pixabay.com/photo/2015/03/26/09/41/salad-690254_640.jpg"
  },

  {
    id: 10,
    name: "Chicken & Rice Bowl",
    ingredients: ["Chicken", "Brown rice", "Pepper", "Salt"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 510,
    protein: 38,
    carbs: 60,
    fat: 10,
    serving: "1 bowl",
    mealType: "lunch",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["gym_meal"],
    image: "https://cdn.pixabay.com/photo/2016/11/21/15/53/rice-1846364_640.jpg"
  },

  {
    id: 11,
    name: "Avocado Toast",
    ingredients: ["Whole grain bread", "Avocado", "Salt", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 260,
    protein: 6,
    carbs: 26,
    fat: 14,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["healthy_fats"],
    image: "https://cdn.pixabay.com/photo/2017/04/25/21/23/avocado-2260921_640.jpg"
  },

  {
    id: 12,
    name: "Vegetable Stir Fry",
    ingredients: ["Broccoli", "Carrot", "Bell pepper", "Tofu", "Soy sauce"],
    type: "veg",
    goal: "weight_loss",
    calories: 220,
    protein: 12,
    carbs: 28,
    fat: 7,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["vegan"],
    image: "https://cdn.pixabay.com/photo/2014/10/19/20/59/vegetables-494821_640.jpg"
  },

  {
    id: 13,
    name: "Quinoa Salad",
    ingredients: ["Quinoa", "Cucumber", "Tomato", "Olive oil"],
    type: "veg",
    goal: "weight_loss",
    calories: 300,
    protein: 11,
    carbs: 34,
    fat: 9,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["plant_protein"],
    image: "https://cdn.pixabay.com/photo/2017/06/14/10/31/quinoa-2400513_640.jpg"
  },

  {
    id: 14,
    name: "Green Smoothie",
    ingredients: ["Spinach", "Banana", "Almond milk"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 3,
    carbs: 35,
    fat: 3,
    mealType: "snack",
    prepTime: "3 min",
    difficulty: "easy",
    tags: ["detox"],
    image: "https://cdn.pixabay.com/photo/2015/09/09/18/45/smoothie-932120_640.jpg"
  },

  {
    id: 15,
    name: "Chickpea Curry",
    ingredients: ["Chickpeas", "Tomato", "Onion", "Garlic", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 260,
    protein: 13,
    carbs: 36,
    fat: 7,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["indian", "vegan"],
    image: "https://cdn.pixabay.com/photo/2020/05/02/06/23/chickpeas-5118386_640.jpg"
  },

  {
    id: 16,
    name: "Fruit Salad",
    ingredients: ["Apple", "Banana", "Grapes", "Orange"],
    type: "veg",
    goal: "weight_loss",
    calories: 150,
    protein: 2,
    carbs: 34,
    fat: 0,
    mealType: "snack",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["healthy"],
    image: "https://cdn.pixabay.com/photo/2016/03/05/19/02/salad-1239247_640.jpg"
  },

  {
    id: 17,
    name: "Tofu Scramble",
    ingredients: ["Tofu", "Turmeric", "Spinach"],
    type: "veg",
    goal: "weight_loss",
    calories: 210,
    protein: 16,
    carbs: 8,
    fat: 12,
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["vegan"],
    image: "https://cdn.pixabay.com/photo/2020/05/05/07/41/tofu-5132715_640.jpg"
  },

  {
    id: 18,
    name: "Grilled Fish",
    ingredients: ["White fish", "Lemon", "Garlic", "Pepper"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 250,
    protein: 30,
    carbs: 2,
    fat: 13,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["omega_3"],
    image: "https://cdn.pixabay.com/photo/2016/01/02/00/32/fish-1114062_640.jpg"
  },

  {
    id: 19,
    name: "Banana Peanut Butter Toast",
    ingredients: ["Banana", "Whole wheat bread", "Peanut butter"],
    type: "veg",
    goal: "weight_gain",
    calories: 360,
    protein: 12,
    carbs: 42,
    fat: 16,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["bulk"],
    image: "https://cdn.pixabay.com/photo/2018/02/16/16/08/bread-3157597_640.jpg"
  },

  {
    id: 20,
    name: "Masala Omelette",
    ingredients: ["Eggs", "Onion", "Tomato", "Coriander", "Chillies"],
    type: "nonveg",
    goal: "weight_loss",
    calories: 220,
    protein: 16,
    carbs: 5,
    fat: 14,
    mealType: "breakfast",
    prepTime: "8 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2017/03/21/16/00/omelette-2166019_640.jpg"
  },

  {
    id: 21,
    name: "Vegetable Soup",
    ingredients: ["Carrot", "Broccoli", "Beans", "Vegetable broth"],
    type: "veg",
    goal: "weight_loss",
    calories: 120,
    protein: 4,
    carbs: 20,
    fat: 2,
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["low_calorie"],
    image: "https://cdn.pixabay.com/photo/2015/10/23/21/02/soup-1008157_640.jpg"
  },

  {
    id: 22,
    name: "Chia Seed Pudding",
    ingredients: ["Chia seeds", "Milk", "Honey", "Strawberries"],
    type: "veg",
    goal: "weight_loss",
    calories: 250,
    protein: 8,
    carbs: 29,
    fat: 11,
    mealType: "breakfast",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["fiber"],
    image: "https://cdn.pixabay.com/photo/2017/03/19/01/00/chia-2159352_640.jpg"
  },

  {
    id: 23,
    name: "Vegetable Upma",
    ingredients: ["Rava", "Carrot", "Peas", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 280,
    protein: 7,
    carbs: 46,
    fat: 7,
    mealType: "breakfast",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2023/01/12/09/00/upma-7713413_640.jpg"
  },

  {
    id: 24,
    name: "Grilled Paneer Tikka",
    ingredients: ["Paneer", "Spices", "Curd"],
    type: "veg",
    goal: "weight_gain",
    calories: 350,
    protein: 21,
    carbs: 8,
    fat: 24,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "medium",
    tags: ["indian", "high_protein"],
    image: "https://cdn.pixabay.com/photo/2023/06/06/10/52/paneer-tikka-8043682_640.jpg"
  },

  {
    id: 25,
    name: "Brown Rice Bowl",
    ingredients: ["Brown rice", "Beans", "Corn", "Peas"],
    type: "veg",
    goal: "weight_gain",
    calories: 410,
    protein: 12,
    carbs: 72,
    fat: 6,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "easy",
    tags: ["complex_carbs"],
    image: "https://cdn.pixabay.com/photo/2016/11/21/15/53/rice-1846364_640.jpg"
  },

  {
    id: 26,
    name: "Sautéed Spinach",
    ingredients: ["Spinach", "Garlic", "Olive oil"],
    type: "veg",
    goal: "weight_loss",
    calories: 120,
    protein: 5,
    carbs: 8,
    fat: 7,
    mealType: "dinner",
    prepTime: "5 min",
    difficulty: "easy",
    tags: ["nutrient_dense"],
    image: "https://cdn.pixabay.com/photo/2021/01/13/20/20/spinach-5917715_640.jpg"
  },

  {
    id: 27,
    name: "Broccoli Soup",
    ingredients: ["Broccoli", "Milk", "Black pepper"],
    type: "veg",
    goal: "weight_loss",
    calories: 180,
    protein: 7,
    carbs: 20,
    fat: 7,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["fiber"],
    image: "https://cdn.pixabay.com/photo/2017/05/23/22/36/broccoli-2339618_640.jpg"
  },

  {
    id: 28,
    name: "Cottage Cheese Salad",
    ingredients: ["Paneer", "Lettuce", "Tomato"],
    type: "veg",
    goal: "weight_gain",
    calories: 260,
    protein: 20,
    carbs: 14,
    fat: 12,
    mealType: "lunch",
    prepTime: "8 min",
    difficulty: "easy",
    tags: ["protein"],
    image: "https://cdn.pixabay.com/photo/2017/05/23/12/48/salad-2338824_640.jpg"
  },

  {
    id: 29,
    name: "Peanut Chutney",
    ingredients: ["Peanuts", "Garlic", "Red chilli"],
    type: "veg",
    goal: "weight_gain",
    calories: 210,
    protein: 9,
    carbs: 8,
    fat: 18,
    mealType: "snack",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["healthy_fats"],
    image: "https://cdn.pixabay.com/photo/2014/12/15/13/40/peanuts-569076_640.jpg"
  },

  {
    id: 30,
    name: "Steamed Dhokla",
    ingredients: ["Gram flour", "Yogurt", "Spices"],
    type: "veg",
    goal: "weight_loss",
    calories: 150,
    protein: 6,
    carbs: 22,
    fat: 4,
    mealType: "snack",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2020/03/22/07/22/dhokla-4956022_640.jpg"
  },

  {
    id: 31,
    name: "Vegetable Khichdi",
    ingredients: ["Rice", "Lentils", "Vegetables"],
    type: "veg",
    goal: "weight_loss",
    calories: 310,
    protein: 13,
    carbs: 54,
    fat: 4,
    mealType: "dinner",
    prepTime: "30 min",
    difficulty: "easy",
    tags: ["indian", "comfort"],
    image: "https://cdn.pixabay.com/photo/2020/11/03/07/15/khichdi-5708658_640.jpg"
  },

  {
    id: 32,
    name: "Egg Fried Rice (Healthy)",
    ingredients: ["Egg", "Brown rice", "Peas"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 480,
    protein: 22,
    carbs: 58,
    fat: 14,
    mealType: "lunch",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["high_protein"],
    image: "https://cdn.pixabay.com/photo/2015/03/26/09/39/fried-rice-690254_640.jpg"
  },

  {
    id: 33,
    name: "Poha",
    ingredients: ["Flattened rice", "Peas", "Onion", "Turmeric"],
    type: "veg",
    goal: "weight_loss",
    calories: 230,
    protein: 5,
    carbs: 40,
    fat: 5,
    mealType: "breakfast",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2020/08/28/07/38/poha-5522131_640.jpg"
  },

  {
    id: 34,
    name: "Lemon Coriander Soup",
    ingredients: ["Coriander", "Lemon", "Vegetables"],
    type: "veg",
    goal: "weight_loss",
    calories: 90,
    protein: 3,
    carbs: 14,
    fat: 2,
    mealType: "dinner",
    prepTime: "15 min",
    difficulty: "easy",
    tags: ["detox"],
    image: "https://cdn.pixabay.com/photo/2017/06/02/18/24/soup-2368029_640.jpg"
  },

  {
    id: 35,
    name: "Hummus Bowl",
    ingredients: ["Chickpeas", "Tahini", "Olive oil", "Lemon"],
    type: "veg",
    goal: "weight_loss",
    calories: 280,
    protein: 10,
    carbs: 24,
    fat: 14,
    mealType: "snack",
    prepTime: "10 min",
    difficulty: "easy",
    tags: ["mediterranean"],
    image: "https://cdn.pixabay.com/photo/2017/05/23/12/48/hummus-2338825_640.jpg"
  },

  {
    id: 36,
    name: "Dal Tadka",
    ingredients: ["Lentils", "Garlic", "Ghee", "Spices"],
    type: "veg",
    goal: "weight_gain",
    calories: 320,
    protein: 18,
    carbs: 34,
    fat: 12,
    mealType: "dinner",
    prepTime: "25 min",
    difficulty: "easy",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2020/05/16/08/58/dal-5179885_640.jpg"
  },

  {
    id: 37,
    name: "Steamed Green Beans",
    ingredients: ["Green beans", "Salt"],
    type: "veg",
    goal: "weight_loss",
    calories: 90,
    protein: 3,
    carbs: 12,
    fat: 2,
    mealType: "lunch",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["light"],
    image: "https://cdn.pixabay.com/photo/2018/03/17/05/25/green-beans-3231934_640.jpg"
  },

  {
    id: 38,
    name: "Egg Curry",
    ingredients: ["Eggs", "Tomato", "Onion", "Spices"],
    type: "nonveg",
    goal: "weight_gain",
    calories: 350,
    protein: 18,
    carbs: 14,
    fat: 22,
    mealType: "dinner",
    prepTime: "20 min",
    difficulty: "medium",
    tags: ["indian"],
    image: "https://cdn.pixabay.com/photo/2023/09/11/14/29/egg-curry-8246773_640.jpg"
  },

  {
    id: 39,
    name: "Protein Smoothie",
    ingredients: ["Milk", "Banana", "Protein powder"],
    type: "veg",
    goal: "weight_gain",
    calories: 420,
    protein: 32,
    carbs: 48,
    fat: 10,
    mealType: "snack",
    prepTime: "3 min",
    difficulty: "easy",
    tags: ["shake"],
    image: "https://cdn.pixabay.com/photo/2017/03/27/14/56/smoothie-2176105_640.jpg"
  },

  {
    id: 40,
    name: "Veg Sandwich",
    ingredients: ["Whole wheat bread", "Cucumber", "Tomato", "Mint chutney"],
    type: "veg",
    goal: "weight_loss",
    calories: 210,
    protein: 6,
    carbs: 32,
    fat: 6,
    mealType: "snack",
    prepTime: "7 min",
    difficulty: "easy",
    tags: ["light"],
    image: "https://cdn.pixabay.com/photo/2017/05/07/08/56/sandwich-2292536_640.jpg"
  }
];
